Item list
Gods-Of-ACM/frontendv2 pull request #23
Opened 2018-05-02 05:08 UTC by bsonge

ListView:  Pass in an array of objects, it picks out the first image it finds and plops it in the left-hand side or displays an 'image not found' image.  Displays data in a tidy list.

Future goals: Pages?

2018-05-02 16:24 UTC, Quinn-Donnelly requested changes
Investigate bug we added it to the search page and passed it the same array that was being past to the ItemTable. When this was done the list was generated but was not showing data.

2018-05-02 16:34 UTC, wrejcodes commented on app/components/ItemList/index.js
> +                <td>{obj[key] || ''}</td>
There is a bug around here preventing the data to be displayed. I was able to get it to display the data by moving  the stuff within braces from line 43 to right after the closing strong tag on line 42. Need further validation that this fixes it

2018-05-02 21:53 UTC, wrejcodes requested changes
After these issues are fixed I think it will be good.

2018-05-03 00:23 UTC, Jubstron approved these changes
I don't have the component to test. So I hesitate to approve this, but I don't see any glaring issues at the moment

2018-05-03 20:15 UTC, Quinn-Donnelly commented
Merging so i can work with it on my end since the files don;t change pages shouldn't break server.

2018-05-03 20:15 UTC, merged